import re

print("=== SQL STORED PROCEDURE ANALYSIS ===")
print()

with open('/home/ubuntu/sql_procedures/SQLЧpГXГgГAГhГvГНГVБ[ГWГГВ╞К╓РФ/Ukeharai.Update_Month_Data.txt', 'r', encoding='utf-8') as f:
    sql_content = f.read()

print("1. STORED PROCEDURE PARAMETER ANALYSIS:")
print("   Parameters received from VB.NET:")
print("   - @S_ToriCd: NVARCHAR(8) - Trading Partner Code")
print("   - @D_ExecYYYYMMDD: Date - Execution Date")
print("   - @ID_User: NVARCHAR(50) - User ID")
print("   - @D_UpdateTime: DateTime - Update Time")
print("   - @ID_Func: NVARCHAR(50) - Function ID")
print()

print("2. CRITICAL VARIABLE DECLARATIONS (Lines 33-42):")
print("   - @S_Zaikosu: NVARCHAR(7) - Stock Quantity as STRING")
print("   - @S_Ukesu: NVARCHAR(7) - Received Quantity as STRING")
print("   - @S_Harasu: NVARCHAR(7) - Paid Quantity as STRING")
print("   - @I_Zaikosu: numeric(7, 0) - Stock Quantity as NUMERIC")
print("   - @I_Ukesu: numeric(7, 0) - Received Quantity as NUMERIC")
print("   - @I_Harasu: numeric(7, 0) - Paid Quantity as NUMERIC")
print()

print("3. ARITHMETIC OVERFLOW ROOT CAUSE (Lines 130-132):")
print("   SQL Code:")
print("   SET @I_Zaikosu = CONVERT(numeric(7, 0), @S_Zaikosu)")
print("   SET @I_Ukesu = CONVERT(numeric(7, 0), @S_Ukesu)")
print("   SET @I_Harasu = CONVERT(numeric(7, 0), @S_Harasu)")
print()
print("   PROBLEM:")
print("   - @S_Zaikosu is NVARCHAR(7) - can only hold 7 characters")
print("   - Data contains values like 9,999,999 (7 digits)")
print("   - When SQL Server tries to CONVERT '9999999' to numeric(7,0)")
print("   - The numeric(7,0) type can only hold values up to 9,999,999")
print("   - But the conversion process itself may cause overflow")
print()

print("4. DATA TYPE CONSTRAINT ANALYSIS:")
print("   - NVARCHAR(7): Maximum 7 characters")
print("   - numeric(7,0): Maximum 7 digits, no decimal places")
print("   - Maximum value for numeric(7,0): 9,999,999")
print("   - Our data contains exactly: 9,999,999")
print("   - This is at the absolute limit of the data type")
print()

print("5. CURSOR PROCESSING FLOW:")
print("   - Lines 50-109: Cursor selects data from T_UKEHARAIJISSEKI")
print("   - Line 112: FETCH data into NVARCHAR(7) variables")
print("   - Lines 130-132: CONVERT NVARCHAR to numeric - OVERFLOW HERE")
print("   - Line 141: INSERT converted values into table")
print()

print("6. DATETIME PARAMETER HANDLING:")
print("   - @D_UpdateTime: DateTime parameter from VB.NET")
print("   - VB.NET sends: Conversions.ToString(DateAndTime.Now)")
print("   - SQL receives as DateTime, no conversion issues here")
print("   - This is NOT the source of the arithmetic overflow")
print()

print("7. EXACT ERROR MECHANISM:")
print("   A. VB.NET calls stored procedure with DateTime parameter")
print("   B. Stored procedure fetches data with large values (9,999,999)")
print("   C. FETCH puts '9999999' into @S_Zaikosu NVARCHAR(7)")
print("   D. CONVERT(numeric(7,0), @S_Zaikosu) attempts conversion")
print("   E. SQL Server arithmetic overflow during CONVERT operation")
print("   F. Error: 'arithmetic overflow converting expression to nvarchar'")
print()

print("8. WHY 'CONVERTING TO NVARCHAR' ERROR MESSAGE:")
print("   - SQL Server error messages can be misleading")
print("   - The overflow occurs during numeric conversion")
print("   - But error message refers to 'nvarchar' conversion")
print("   - This is likely due to internal SQL Server error handling")
